### ISSUE TITLE
TODO List:

### ISSUE THREAD

**Issue by shashank-sharma** [shashank-sharma/shashank-sharma.github.io#3]
- [ ] Data blog

- [ ] Home page revamp

- [x] Website logo ?

- [ ] Anime list

- [ ] Books to read list

- [ ] Tag based blogs

- [ ] Terminal finalize working

- [ ] Ability to CRUD TODO list

- [ ] Allow to make PR of it
